# .travis.yml
# Configure Travis CI service to build SOCI library
# Mateusz Loskot <mateusz@loskot.net>, http://github.com/SOCI
#
language: cpp

# Testing against two compilers will create (at least) 2 rows in build matrix
# http://about.travis-ci.org/docs/user/languages/cpp/
compiler:
  - g++
  - clang

branches:
  only:
    - testing

services:
  - mysql
  - postgresql

before_install: ./bin/ci/before_install.sh
before_script: ./bin/ci/before_script.sh
script: ./bin/ci/script.sh

notifications:
  email:
    recipients:
      - toonen@alcf.anl.gov
  on_success: change # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always
